import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { dir } from 'i18next';
import { languages } from '../i18n/settings';
import '../globals.css';
import QueryProvider from '../QueryProvider';
import ToasterProvider from '../ToasterProvider';
import { Footer } from '@/components/layouts/Footer';
import { Header } from '@/components/layouts/Header';

const inter = Inter({ subsets: ['cyrillic'] });

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
  params: { lng: string };
}) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className} suppressHydrationWarning>
        <ToasterProvider>
          <QueryProvider>
            <main
              style={{
                marginTop: '64px',
              }}
            >
              <Header />
              {children}
              <Footer lng={lng} />
            </main>
          </QueryProvider>
        </ToasterProvider>
      </body>
    </html>
  );
}
