import type { Metadata } from "next";
import { Roboto, Noto_Sans_KR } from "next/font/google";
import { dir } from "i18next";
import { languages } from "../i18n/settings";
import "../globals.css";
import QueryProvider from "../QueryProvider";
import ToasterProvider from "../ToasterProvider";
import { Footer } from "@/components/layouts/Footer";
import { Header } from "@/components/layouts/Header";

const notoSansKr = Noto_Sans_KR({
  // preload: true, 기본값
  subsets: ["latin"], // 또는 preload: false
  weight: ["100", "400", "700", "900"], // 가변 폰트가 아닌 경우, 사용할 fontWeight 배열
});

const roboto = Roboto({
  subsets: ["latin"], // preload에 사용할 subsets입니다.
  weight: ["100", "400", "700"],
  variable: "--roboto", // CSS 변수 방식으로 스타일을 지정할 경우에 사용합니다.
});

export const cls = (...classnames: string[]) => {
  return classnames.join(" ");
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
  params: { lng: string };
}) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body
        className={cls(notoSansKr.className, roboto.className)}
        suppressHydrationWarning
      >
        <ToasterProvider>
          <QueryProvider>
            <main className="font-roboto max-w-screen-2xl mx-auto">
              <Header lng={lng} />
              {children}
              <Footer lng={lng} />
            </main>
          </QueryProvider>
        </ToasterProvider>
      </body>
    </html>
  );
}
